services:
  frontend:
    build:
      context: player
      dockerfile: Dockerfile
      tags:
        - "quic-media-frontend:latest"
    volumes:
      - ./cert:/certs
    command: "npx serve dist --ssl-cert /certs/cert.pem --ssl-key /certs/key.pem"
    ports:
      - "3000:3000"
  media:
    build:
      context: .
      dockerfile: Dockerfile.media
      tags:
        - "quic-media:media"
    volumes:
      - ./cert:/certs
    ports:
      - "4443:4443/udp"
  streaming:
    build:
      context: .
      dockerfile: Dockerfile.streaming
      tags:
        - "quic-media:streaming"
    volumes:
      - ./cert:/certs
    ports:
      - "1935:1935"
      - "8443:4443/udp"
